/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserCreateNestedManyWithoutOrganizationsInput } from "./UserCreateNestedManyWithoutOrganizationsInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { ServiceCreateNestedManyWithoutOrganizationsInput } from "./ServiceCreateNestedManyWithoutOrganizationsInput";
import { EnumOrganizationTypes } from "./EnumOrganizationTypes";
@InputType()
class OrganizationCreateInput {
  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutOrganizationsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutOrganizationsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutOrganizationsInput, {
    nullable: true,
  })
  contactPerson?: UserCreateNestedManyWithoutOrganizationsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  createdBy?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  organizationEmail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  organizationPhoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => ServiceCreateNestedManyWithoutOrganizationsInput,
  })
  @ValidateNested()
  @Type(() => ServiceCreateNestedManyWithoutOrganizationsInput)
  @IsOptional()
  @Field(() => ServiceCreateNestedManyWithoutOrganizationsInput, {
    nullable: true,
  })
  services?: ServiceCreateNestedManyWithoutOrganizationsInput;

  @ApiProperty({
    required: true,
    enum: EnumOrganizationTypes,
    isArray: true,
  })
  @IsEnum(EnumOrganizationTypes, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumOrganizationTypes], {
    nullable: true,
  })
  types?: Array<"Nursery" | "Organization">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  webSite?: string | null;
}
export { OrganizationCreateInput };
