/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCampaignTypeArgs } from "./CreateCampaignTypeArgs";
import { UpdateCampaignTypeArgs } from "./UpdateCampaignTypeArgs";
import { DeleteCampaignTypeArgs } from "./DeleteCampaignTypeArgs";
import { CampaignTypeFindManyArgs } from "./CampaignTypeFindManyArgs";
import { CampaignTypeFindUniqueArgs } from "./CampaignTypeFindUniqueArgs";
import { CampaignType } from "./CampaignType";
import { CampaignTypeService } from "../campaignType.service";

@graphql.Resolver(() => CampaignType)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CampaignTypeResolverBase {
  constructor(
    protected readonly service: CampaignTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "read",
    possession: "any",
  })
  async _campaignTypesMeta(
    @graphql.Args() args: CampaignTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CampaignType])
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "read",
    possession: "any",
  })
  async campaignTypes(
    @graphql.Args() args: CampaignTypeFindManyArgs
  ): Promise<CampaignType[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CampaignType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "read",
    possession: "own",
  })
  async campaignType(
    @graphql.Args() args: CampaignTypeFindUniqueArgs
  ): Promise<CampaignType | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CampaignType)
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "create",
    possession: "any",
  })
  async createCampaignType(
    @graphql.Args() args: CreateCampaignTypeArgs
  ): Promise<CampaignType> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CampaignType)
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "update",
    possession: "any",
  })
  async updateCampaignType(
    @graphql.Args() args: UpdateCampaignTypeArgs
  ): Promise<CampaignType | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CampaignType)
  @nestAccessControl.UseRoles({
    resource: "CampaignType",
    action: "delete",
    possession: "any",
  })
  async deleteCampaignType(
    @graphql.Args() args: DeleteCampaignTypeArgs
  ): Promise<CampaignType | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
