/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Tree,
  User,
  Campaign,
  TreeCondition,
  TreeType,
} from "@prisma/client";

export class TreeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.TreeFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeFindManyArgs>
  ): Promise<number> {
    return this.prisma.tree.count(args);
  }

  async findMany<T extends Prisma.TreeFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeFindManyArgs>
  ): Promise<Tree[]> {
    return this.prisma.tree.findMany(args);
  }
  async findOne<T extends Prisma.TreeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeFindUniqueArgs>
  ): Promise<Tree | null> {
    return this.prisma.tree.findUnique(args);
  }
  async create<T extends Prisma.TreeCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeCreateArgs>
  ): Promise<Tree> {
    return this.prisma.tree.create<T>(args);
  }
  async update<T extends Prisma.TreeUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeUpdateArgs>
  ): Promise<Tree> {
    return this.prisma.tree.update<T>(args);
  }
  async delete<T extends Prisma.TreeDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TreeDeleteArgs>
  ): Promise<Tree> {
    return this.prisma.tree.delete(args);
  }

  async findAdaptors(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.tree
      .findUnique({
        where: { id: parentId },
      })
      .adaptors(args);
  }

  async findPlantedBy(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.tree
      .findUnique({
        where: { id: parentId },
      })
      .plantedBy(args);
  }

  async getCampaign(parentId: string): Promise<Campaign | null> {
    return this.prisma.tree
      .findUnique({
        where: { id: parentId },
      })
      .campaign();
  }

  async getCondition(parentId: string): Promise<TreeCondition | null> {
    return this.prisma.tree
      .findUnique({
        where: { id: parentId },
      })
      .condition();
  }

  async getTreeType(parentId: string): Promise<TreeType | null> {
    return this.prisma.tree
      .findUnique({
        where: { id: parentId },
      })
      .treeType();
  }
}
